mixed-port: 2080
allow-lan: false
tcp-concurrent: true
enable-process: true
global-client-fingerprint: chrome
mode: rule
ipv6: true
global-ua: chrome
keep-alive-interval: 25
unified-delay: false
proxies:
- flow: xtls-rprx-vision
  name: REBULLET
  network: tcp
  port:
  reality-opts:
    public-key:
    short-id:
  server:
  servername:
  tcp-opts:
    ip-version: dual
  tls: true
  type: vless
  udp: true
  packet-encoding: xudp
  client-fingerprint: chrome
  uuid:
rules:
- RULE-SET,REJECT,REJECT
- RULE-SET,DIRECT,DIRECT
- RULE-SET,PROXY,PROXY
geodata-mode: true
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat
  geosite: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb
  asn: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb
tun:
  enable: true
  stack: mixed
  dns-hijack:
  - any:53
  - '[::]:53'
  auto-route: true
  auto-detect-interface: true
  strict-route: true
  mtu: 1500
dns:
  enable: true
  prefer-h3: true
  listen: 0.0.0.0:53
  use-hosts: true
  ipv6: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - localhost
  default-nameserver:
  - 9.9.9.9
  - 8.8.8.8
  nameserver:
  - tls://dns.switch.ch#PROXY
  - tls://dns.quad9.net#PROXY
  - tls://dns.google#PROXY
  - tls://one.one.one.one#PROXY
  fallback:
  - tls://dns.switch.ch#PROXY
  - tls://dns.quad9.net#PROXY
  - tls://dns.google#PROXY
  - tls://one.one.one.one#PROXY
  proxy-server-nameserver:
  - tls://dns.switch.ch
  - tls://dns.google
  - tls://one.one.one.one
proxy-groups:
- name: PROXY
  type: url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - REBULLET
rule-providers:
  PROXY:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/UhExooHw/meta-rules-yaml/refs/heads/main/PROXY.yaml
    path: ./rebullet/proxy.yaml
    interval: 86400
  REJECT:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/UhExooHw/meta-rules-yaml/refs/heads/main/REJECT.yaml
    path: ./rebullet/reject.yaml
    interval: 86400
  DIRECT:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/UhExooHw/meta-rules-yaml/refs/heads/main/DIRECT.yaml
    path: ./rebullet/direct.yaml
    interval: 86400
