mixed-port: 10807
allow-lan: true
lan-allowed-ips:
  - 0.0.0.0/0
  - ::/0
bind-address: "*"
mode: rule
log-level: error
ipv6: true
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

geodata-mode: true
geodata-loader: memconservative
geo-update-interval: 24
geox-url:
  geoip: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
  geosite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb"
  asn: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb"

dns:
  enable: true
  use-hosts: true
  listen: 0.0.0.0:1053
  ipv6: true
  default-nameserver:
    - "9.9.9.9"
    - "9.9.9.11"
    - "[2620:fe::9]:53"
    - "[2620:fe::11]:53"
  nameserver:
    - "https://dns.quad9.net/dns-query#PROXY"
    - "https://dns11.quad9.net/dns-query#PROXY"
  fallback:
    - "https://dns.quad9.net/dns-query#PROXY"
    - "https://dns11.quad9.net/dns-query#PROXY"
  direct-nameserver:
    - "9.9.9.9"
    - "9.9.9.11"
    - "[2620:fe::9]:53"
    - "[2620:fe::11]:53"

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]


tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
  device: utun0
  mtu: 1500
  strict-route: true

proxies:
- name: "REBULLET"
  type: socks5
  server: 127.0.0.1
  port: 10808
  udp: true
  xudp: true

rules:
- RULE-SET,REJECT,REJECT
- RULE-SET,DIRECT,DIRECT
- MATCH,PROXY

proxy-groups:
- name: 'PROXY'
  type: 'select'
  interval: 60
  proxies:
  - "REBULLET"
  - "DIRECT"
- name: 'GLOBAL'
  type: 'select'
  interval: 60
  proxies:
  - "REBULLET"
  - "DIRECT"

rule-providers:
  REJECT:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/UhExooHw/meta-rules-yaml/refs/heads/main/REJECT.yaml
    path: ./rebullet/reject.yaml
    interval: 1440
  DIRECT:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/UhExooHw/meta-rules-yaml/refs/heads/main/DIRECT.yaml
    path: ./rebullet/direct.yaml
    interval: 1440
