mixed-port: 2080
allow-lan: false
tcp-concurrent: true
enable-process: true
global-client-fingerprint: chrome
mode: rule
log-level: error
ipv6: true
keep-alive-interval: 25
unified-delay: false
profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: true
  sniff:
    HTTP:
      ports:
      - 80
      - 8080-8880
      override-destination: true
    TLS:
      ports:
      - 443
      - 8443
    QUIC:
      ports:
      - 443
      - 8443
proxies:
- flow: xtls-rprx-vision
  name: REBULLET
  network: tcp
  port: 
  reality-opts:
    public-key:
    short-id:
  server:
  servername:
  tcp-opts:
    ip-version: dual
  tls: true
  type: vless
  udp: true
  packet-encoding: xudp
  client-fingerprint: chrome
  uuid:
rules:
- RULE-SET,REJECT,REJECT
- RULE-SET,DIRECT,DIRECT
- RULE-SET,PROXY,PROXY
geodata-mode: true
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat
  geosite: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb
  asn: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb
tun:
  enable: true
  stack: system
  dns-hijack:
  - any:53
  auto-route: true
  auto-detect-interface: true
  strict-route: true
  mtu: 1500
dns:
  enable: true
  prefer-h3: true
  use-hosts: true
  use-system-hosts: true
  listen: 127.0.0.1:6868
  ipv6: true
  enhanced-mode: redir-host
  default-nameserver:
    - '9.9.9.9'
    - '8.8.8.8'
  proxy-server-nameserver:
    - '9.9.9.9'
    - '8.8.8.8'
  nameserver:
    - 'tls://dns.quad9.net#PROXY'
    - 'tls://dns.google#PROXY'
proxy-groups:
- name: PROXY
  type: select
  proxies:
  - REBULLET
rule-providers:
  PROXY:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/UhExooHw/meta-rules-yaml/refs/heads/main/PROXY.yaml
    path: ./rebullet/proxy.yaml
    interval: 86400
  REJECT:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/UhExooHw/meta-rules-yaml/refs/heads/main/REJECT.yaml
    path: ./rebullet/reject.yaml
    interval: 86400
  DIRECT:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/UhExooHw/meta-rules-yaml/refs/heads/main/DIRECT.yaml
    path: ./rebullet/direct.yaml
    interval: 86400
