allow-lan: true
bind-address: "*"
mode: rule
log-level: info
ipv6: false
keep-alive-interval: 25
unified-delay: false
tcp-concurrent: true
global-client-fingerprint: chrome

profile:
  store-selected: true
  store-fake-ip: true

geodata-mode: true
geodata-loader: memconservative
geo-update-interval: 24
geox-url:
  geoip: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat"
  geosite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country.mmdb"
  asn: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb"

dns:
  enable: true
  use-hosts: true
  listen: 127.0.0.1:1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - 'localhost'
  default-nameserver:
    - "9.9.9.9"
    - "9.9.9.11"
  nameserver:
    - "tls://dns.quad9.net"
    - "tls://dns11.quad9.net"
  fallback:
    - "tls://dns.quad9.net"
    - "tls://dns11.quad9.net"
  direct-nameserver:
    - "9.9.9.9"
    - "9.9.9.11"

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: false
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]


tun:
  enable: true
  stack: mixed
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
    - tcp://any:53
  device: utun0
  mtu: 1500
  strict-route: true

proxies:
- name: "REBULLET"
  type: vless
  server: ""
  port: 443
  udp: true
  uuid: ""
  flow: xtls-rprx-vision
  packet-encoding: xudp
  tls: true
  servername: ""
  client-fingerprint: chrome
  reality-opts:
    public-key: ""
    short-id: ""
  network: tcp
  smux:
    enabled: false

rules:
- RULE-SET,REJECT,REJECT
- RULE-SET,DIRECT,DIRECT
## - RULE-SET,PROXY,PROXY
- MATCH,PROXY

proxy-groups:
- name: "PROXY"
  type: select
  proxies:
  - "REBULLET"
  - "DIRECT"
- name: "GLOBAL"
  type: select
  proxies:
  - "REBULLET"
  - "DIRECT"

rule-providers:
  PROXY:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/UhExooHw/meta-rules-yaml/refs/heads/main/PROXY.yaml
    path: ./rebullet/proxy.yaml
    interval: 86400
  REJECT:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/UhExooHw/meta-rules-yaml/refs/heads/main/REJECT.yaml
    path: ./rebullet/reject.yaml
    interval: 86400
  DIRECT:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/UhExooHw/meta-rules-yaml/refs/heads/main/DIRECT.yaml
    path: ./rebullet/direct.yaml
    interval: 86400
